export enum ERROR_CODES {
  UNAUTHENTICATED = 'unauthenticated',
  FORBIDDEN = 'forbidden',
  GENERAL_EXCEPTION = 'generalException',
  USER_NOT_FOUND = 'userNotFound',
  BANK_ACCOUNT_NOT_FOUND = 'bankAccountNotFound',
  PAYMENT_NOT_FOUND = 'paymentNotFound',
  PAYMENT_NOT_CANCELLABLE = 'paymentNotCancellable',
  TRANSACTION_NOT_FOUND = 'transactionNotFound',
  ITEM_ALREADY_EXISTS = 'itemAlreadyExists',
  INVALID_REQUEST = 'invalidRequest',
  SOURCE_ACCOUNT_NOT_FOUND = 'sourceAccountNotFound',
  DESTINATION_ACCOUNT_NOT_FOUND = 'destinationAccountNotFound',
  INVALID_AMOUNT = 'invalidAmount',
  INSUFFICIENT_BALANCE = 'insufficientBalance',
  IDEMPOTENCY_KEY_REUSED = 'idempotencyKeyReused',
  IDEMPOTENT_REQUEST_IN_PROGRESS = 'idempotentRequestInProgress',
}
